# Generated by Django 2.2.12 on 2020-08-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200815_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blog',
        ),
    ]
