# Generated by Django 2.2.12 on 2020-08-16 18:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Description2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
