# Generated by Django 2.2.12 on 2020-08-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200817_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Description2',
        ),
    ]
