# Generated by Django 2.2.12 on 2020-08-10 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20200810_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='artikel', to=settings.AUTH_USER_MODEL),
        ),
    ]
