# Generated by Django 2.2.12 on 2020-08-10 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_artikel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artikel', to=settings.AUTH_USER_MODEL),
        ),
    ]
