# Generated by Django 2.2.12 on 2020-08-15 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200813_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artikel', to='blog.Category'),
        ),
    ]
